import Link from "next/link";
import "./globals.css";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogOutBtn from "./LogOutBtn";
import { cookies } from "next/headers";
import DarkMode from "./DarkMode";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  let cookie = cookies().get("mode");

  return (
    <html>
      <body
        className={
          cookie != undefined && cookie.value == "dark" ? "dark-mode" : ""
        }
      >
        <div className="navbar">
          <Link href="/" className="logo">
            게시판
          </Link>
          <Link href="/list">List</Link>
          {session ? (
            <div>
              <div className="name">{session.user.name}</div>
              <LogOutBtn />
            </div>
          ) : (
            <LoginBtn />
          )}
          <DarkMode />
        </div>
        {children}
      </body>
    </html>
  );
}
